<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Async&Await_A</title>
</head>
<body>
  <script>
    // 异步函数

    // ES8 的 async/await 旨在解决利用异步结构组织代码的问题。为此，ES 对函数进行了扩展，
    // 为其增加了两个新关键字：async 和 await。

    // 1. async
    // async 关键字用于声明异步函数。这个关键字可以用在函数声明、函数表达式、箭头函数和方法上：
    async function fooAsync1() {} 
    let br = async function() {}; 
    let bz = async () => {}; 
    class Qux { 
      async qux() {} 
    }

    // 使用 async 关键字可以让函数具有异步特征，但总体上其代码仍然是同步求值的。
    // 而在参数或闭包方面，异步函数仍然具有普通 JavaScript 函数的正常行为。
    async function fooAsync2() { 
      console.log(1); 
    }
    fooAsync2(); 
    console.log(2);
    // 1 
    // 2

    // 不过，异步函数如果使用 return 关键字返回了值（如果没有 return 则会返回 undefined），
    // 这个值会被 Promise.resolve() 包装成一个期约对象。异步函数始终返回期约对象。
    // 在函数外部调用这个函数可以得到它返回的期约：
    async function fooAsync3() { 
      console.log(11); 
      return 22; 
    } 
    fooAsync3().then(console.log); // 给返回的期约添加一个解决处理程序
    console.log(33); 
    // 11
    // 33
    // 22

    // 直接返回一个期约对象也是一样的： 
    async function fooAsync4() { 
      console.log(111); 
      return Promise.resolve(222); 
    } 
    fooAsync4().then(console.log); // 给返回的期约添加一个解决处理程序
    console.log(333); 
    // 111
    // 333
    // 222

    // 异步函数的返回值期待（但实际上并不要求）一个实现 thenable 接口的对象，但常规的值也可以。
    // 如果返回的是实现 thenable 接口的对象，则这个对象可以由提供给 then() 的处理程序“解包”。
    // 如果不是，则返回值就被当作已经解决的期约。
    async function fooAsync() { 
      return 'foo'; // 返回一个原始值 
    } 
    fooAsync().then(console.log); // foo

    async function barAsync() { 
      return ['bar']; // 返回一个没有实现 thenable 接口的对象
    } 
    barAsync().then(console.log); // ['bar']
    
    async function bazAsync() { 
      const thenable = { 
        then(callback) { callback('baz'); } 
      }; 
      return thenable; // 返回一个实现了 thenable 接口的非期约对象
    } 
    bazAsync().then(console.log); // baz

    async function quxAsync() { 
      return Promise.resolve('qux'); // 返回一个期约
    } 
    quxAsync().then(console.log); // qux

    // 与在期约处理程序中一样，在异步函数中抛出错误会返回拒绝的期约：
    async function fAsync1() { 
      console.log(1111); 
      throw 2222; 
    } 
    fAsync1().catch(console.log); // 给返回的期约添加一个拒绝处理程序
    console.log(3333); 
    // 1111
    // 3333
    // 2222

    // 不过，拒绝期约的错误不会被异步函数捕获：
    async function fAsync2() { 
      console.log(11111); 
      Promise.reject(22222); 
    } 
    fAsync2().catch(console.log); // 给返回的期约添加一个拒绝处理程序
    console.log(33333); 
    // 11111
    // 33333
    // Uncaught (in promise): 22222

    // 2. await
    // 因为异步函数主要针对不会马上完成的任务，所以自然需要一种暂停和恢复执行的能力。
    // 使用 await 关键字可以暂停异步函数代码的执行，等待期约解决。
    let p = new Promise((resolve, reject) => setTimeout(resolve, 1000, 3)); 
    p.then((x) => console.log(x)); // 3 

    // 使用 async/await 可以写成这样：
    async function fooAwait() {
      let p = new Promise((resolve, reject) => setTimeout(resolve, 1000, 3)); 
      console.log(await p); 
    }
    fooAwait1(); // 3

    // await 关键字会暂停执行异步函数后面的代码，让出 JavaScript 运行时的执行线程。这个行为与
    // 生成器函数中的 yield 关键字是一样的。await 关键字同样是尝试“解包”对象的值，然后将这个值
    // 传给表达式，再异步恢复异步函数的执行。
    // await 关键字的用法与 JavaScript 的一元操作一样。它可以单独使用，也可以在表达式中使用
    async function fooAwait1() { 
      console.log(await Promise.resolve('foo')); // 异步打印"foo" 
    } 
    fooAwait1(); // foo 
    
    async function fooAwait2() { 
      return await Promise.resolve('bar'); // 异步打印"bar" 
    } 
    fooAwait2().then(console.log); // bar 
    
    async function fooAwait3() { 
      await new Promise((resolve, reject) => setTimeout(resolve, 1000)); 
      console.log('baz'); // 1000 毫秒后异步打印"baz" 
    } 
    fooAwait3(); // baz（1000 毫秒后）

    // await 关键字期待（但实际上并不要求）一个实现 thenable 接口的对象，但常规的值也可以。
    // 如果是实现 thenable 接口的对象，则这个对象可以由 await 来“解包”。
    // 如果不是，则这个值就被当作已经解决的期约。
    async function fooAwait() { 
      console.log(await 'foo'); // 等待一个原始值 
    } 
    fooAwait(); // foo
    
    async function barAwait() { 
      console.log(await ['bar']); // 等待一个没有实现 thenable 接口的对象
    } 
    barAwait(); // ['bar']
    
    async function bazAwait() { 
      const thenable = { 
        then(callback) { callback('baz'); } // 等待一个实现了 thenable 接口的非期约对象
      }; 
      console.log(await thenable); 
    } 
    bazAwait(); // baz 
    
    async function quxAwait() { 
      console.log(await Promise.resolve('qux')); // 等待一个期约
    } 
    quxAwait(); // qux

    // 等待会抛出错误的同步操作，会返回拒绝的期约：
    async function fAwait1() {
      console.log(111111); 
      await (() => { throw 222222; })();
    } 
    fAwait1().catch(console.log); // 给返回的期约添加一个拒绝处理程序
    console.log(333333); 
    // 111111
    // 333333
    // 222222

    // 单独的 Promise.reject()不会被异步函数捕获，而会抛出未捕获错误。
    // 不过，对拒绝的期约使用 await 则会释放（unwrap）错误值（将拒绝期约返回）：
    async function fAwait2() { 
      console.log(1111111); 
      await Promise.reject(2222222); 
      console.log(3333333); // 这行代码不会执行
    } 
    fAwait2().catch(console.log); // 给返回的期约添加一个拒绝处理程序
    console.log(4444444); 
    // 1111111
    // 4444444
    // 2222222

    // 3. await 的限制
    // await 关键字必须在异步函数中使用，不能在顶级上下文如 <script> 标签或模块中使用。
    // 不过，定义并立即调用异步函数是没问题的，下面两段代码实际相同：
    async function foo() { 
      console.log(await Promise.resolve(3)); 
    } 
    foo(); // 3 
    
    (async function() { // 立即调用的异步函数表达式
      console.log(await Promise.resolve(3)); 
    })(); // 3 

    // 此外，异步函数的特质不会扩展到嵌套函数。因此，await 关键字也只能直接出现在
    // 异步函数的定义中。在同步函数内部使用 await 会抛出 SyntaxError。
  </script>
</body>
</html>